Rewrite the health-check module
It now uses sbt-mu-srcgen to generate code from a .proto file, instead
of defining the service in code with the macro annotation. That will
allow us to cross-build this module for Scala 3.

Because it's based on the official Protobuf definition taken from the
gRPC docs, it's now compliant with the gRPC health check spec:

```
$ ./grpc_health_probe-darwin-amd64 -addr localhost:12345
status: SERVING

$ ./grpc_health_probe-darwin-amd64 -addr localhost:12345 -service A
service unhealthy (responded with "NOT_SERVING")

$ ./grpc_health_probe-darwin-amd64 -addr localhost:12345 -service B
status: SERVING

$ ./grpc_health_probe-darwin-amd64 -addr localhost:12345 -service C
error: health rpc failed: rpc error: code = NotFound desc =

```